// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgIS3Rvc4v0L43b3Au8g3b2BLZDsIi__E',
    appId: '1:985629934366:web:fbee424d61172e607fff0f',
    messagingSenderId: '985629934366',
    projectId: 'tarefinhas-8bsfd',
    authDomain: 'tarefinhas-8bsfd.firebaseapp.com',
    databaseURL: 'https://tarefinhas-8bsfd-default-rtdb.firebaseio.com',
    storageBucket: 'tarefinhas-8bsfd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX7saiY6etbo1rVXTfdzUL3BSAQZYF3aM',
    appId: '1:985629934366:android:57e43cfccd4fe9777fff0f',
    messagingSenderId: '985629934366',
    projectId: 'tarefinhas-8bsfd',
    databaseURL: 'https://tarefinhas-8bsfd-default-rtdb.firebaseio.com',
    storageBucket: 'tarefinhas-8bsfd.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgIS3Rvc4v0L43b3Au8g3b2BLZDsIi__E',
    appId: '1:985629934366:web:a395553bab8854697fff0f',
    messagingSenderId: '985629934366',
    projectId: 'tarefinhas-8bsfd',
    authDomain: 'tarefinhas-8bsfd.firebaseapp.com',
    databaseURL: 'https://tarefinhas-8bsfd-default-rtdb.firebaseio.com',
    storageBucket: 'tarefinhas-8bsfd.firebasestorage.app',
  );
}
